{% set name = "pymongo_inmemory" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymongo_inmemory-{{ version }}.tar.gz
  sha256: 09c67901b91b43e86b2af6979a25c167171ce0c64e7473c5d96734828f470086

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - poetry-core >=0.12
    - pip
  run:
    - python >=3.9
    - pymongo *

test:
  imports:
    - pymongo_inmemory
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kaizendorks/pymongo_inmemory
  summary: A mongo mocking library with an ephemeral MongoDB running in memory.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
